In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("DATA/loan_data.csv")

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,RATE_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,RATE_INTEREST_PRIVILEGED,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.022,0.0198,0.0,0.0,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.00,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1038818,Consumer loans,9251.775,179055.0,179055.0,0.0,179055.0,SATURDAY,9,Y,1,0.000000,NaN,NaN,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,NaN,900000.0,FRIDAY,12,Y,1,NaN,NaN,NaN,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,0.0,337500.0,SUNDAY,17,Y,1,0.000000,NaN,NaN,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.079,0.0554,0.0,0.0,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.01,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,6885.0,68809.5,SATURDAY,15,Y,1,0.100061,NaN,NaN,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1564014,Consumer loans,5357.250,24282.0,20106.0,4860.0,24282.0,FRIDAY,5,Y,1,0.212008,NaN,NaN,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0

In [5]:
data.shape

(1413701, 158)

In [6]:
data.duplicated().sum()

0

In [7]:
data.isnull().sum()

SK_ID_CURR                            0
TARGET                                0
NAME_CONTRACT_TYPE_x                  0
CODE_GENDER                           0
FLAG_OWN_CAR                          0
FLAG_OWN_REALTY                       0
CNT_CHILDREN                          0
AMT_INCOME_TOTAL                      0
AMT_CREDIT_x                          0
AMT_ANNUITY_x                        93
AMT_GOODS_PRICE_x                  1208
NAME_TYPE_SUITE_x                  3526
NAME_INCOME_TYPE                      0
NAME_EDUCATION_TYPE                   0
NAME_FAMILY_STATUS                    0
NAME_HOUSING_TYPE                     0
REGION_POPULATION_RELATIVE            0
DAYS_BIRTH                            0
DAYS_EMPLOYED                         0
DAYS_REGISTRATION                     0
DAYS_ID_PUBLISH                       0
OWN_CAR_AGE                      937206
FLAG_MOBIL                            0
FLAG_EMP_PHONE                        0
FLAG_WORK_PHONE                       0
FLAG_CONT_MOBILE                      0
FLAG_PHONE                            0
FLAG_EMAIL                            0
OCCUPATION_TYPE                  457580
CNT_FAM_MEMBERS                       0
REGION_RATING_CLIENT                  0
REGION_RATING_CLIENT_W_CITY           0
WEEKDAY_APPR_PROCESS_START_x          0
HOUR_APPR_PROCESS_START_x             0
REG_REGION_NOT_LIVE_REGION            0
REG_REGION_NOT_WORK_REGION            0
LIVE_REGION_NOT_WORK_REGION           0
REG_CITY_NOT_LIVE_CITY                0
REG_CITY_NOT_WORK_CITY                0
LIVE_CITY_NOT_WORK_CITY               0
ORGANIZATION_TYPE                     0
EXT_SOURCE_1                     796859
EXT_SOURCE_2                       1821
EXT_SOURCE_3                     241842
APARTMENTS_AVG                   711998
BASEMENTAREA_AVG                 824308
YEARS_BEGINEXPLUATATION_AVG      684682
YEARS_BUILD_AVG                  937257
COMMONAREA_AVG                   985199
ELEVATORS_AVG                    749216
ENTRANCES_AVG                    706782
FLOORSMAX_AVG                    698508
FLOORSMIN_AVG                    956660
LANDAREA_AVG                     837173
LIVINGAPARTMENTS_AVG             964350
LIVINGAREA_AVG                   704400
NONLIVINGAPARTMENTS_AVG          979646
NONLIVINGAREA_AVG                775558
APARTMENTS_MODE                  711998
BASEMENTAREA_MODE                824308
YEARS_BEGINEXPLUATATION_MODE     684682
YEARS_BUILD_MODE                 937257
COMMONAREA_MODE                  985199
ELEVATORS_MODE                   749216
ENTRANCES_MODE                   706782
FLOORSMAX_MODE                   698508
FLOORSMIN_MODE                   956660
LANDAREA_MODE                    837173
LIVINGAPARTMENTS_MODE            964350
LIVINGAREA_MODE                  704400
NONLIVINGAPARTMENTS_MODE         979646
NONLIVINGAREA_MODE               775558
APARTMENTS_MEDI                  711998
BASEMENTAREA_MEDI                824308
YEARS_BEGINEXPLUATATION_MEDI     684682
YEARS_BUILD_MEDI                 937257
COMMONAREA_MEDI                  985199
ELEVATORS_MEDI                   749216
ENTRANCES_MEDI                   706782
FLOORSMAX_MEDI                   698508
FLOORSMIN_MEDI                   956660
LANDAREA_MEDI                    837173
LIVINGAPARTMENTS_MEDI            964350
LIVINGAREA_MEDI                  704400
NONLIVINGAPARTMENTS_MEDI         979646
NONLIVINGAREA_MEDI               775558
FONDKAPREMONT_MODE               964374
HOUSETYPE_MODE                   704166
TOTALAREA_MODE                   677541
WALLSMATERIAL_MODE               713386
EMERGENCYSTATE_MODE              665351
OBS_30_CNT_SOCIAL_CIRCLE           3146
DEF_30_CNT_SOCIAL_CIRCLE           3146
OBS_60_CNT_SOCIAL_CIRCLE           3146
DEF_60_CNT_SOCIAL_CIRCLE           3146
DAYS_LAST_PHONE_CHANGE                0
FLAG_DOCUMENT_2                       0
FLAG_DOCUMENT_3                       0
FLAG_DOCUMENT_4                       0
FLAG_DOCUMENT_5                       0
FLAG_DOCUMENT_6                       0
FLAG_DOCUMENT_7                       0
FLAG_DOCUMENT_8                       0
FLAG_DOCUMENT_9                       0
FLAG_DOCUMENT_10                      0
FLAG_DOCUMENT_11                      0
FLAG_DOCUMENT_12                      0
FLAG_DOCUMENT_13                      0
FLAG_DOCUMENT_14                      0
FLAG_DOCUMENT_15                      0
FLAG_DOCUMENT_16                      0
FLAG_DOCUMENT_17                      0
FLAG_DOCUMENT_18                      0
FLAG_DOCUMENT_19                      0
FLAG_DOCUMENT_20                      0
FLAG_DOCUMENT_21                      0
AMT_REQ_CREDIT_BUREAU_HOUR       163627
AMT_REQ_CREDIT_BUREAU_DAY        163627
AMT_REQ_CREDIT_BUREAU_WEEK       163627
AMT_REQ_CREDIT_BUREAU_MON        163627
AMT_REQ_CREDIT_BUREAU_QRT        163627
AMT_REQ_CREDIT_BUREAU_YEAR       163627
SK_ID_PREV                            0
NAME_CONTRACT_TYPE_y                  0
AMT_ANNUITY_y                    307218
AMT_APPLICATION                       0
AMT_CREDIT_y                          1
AMT_DOWN_PAYMENT                 749540
AMT_GOODS_PRICE_y                319525
WEEKDAY_APPR_PROCESS_START_y          0
HOUR_APPR_PROCESS_START_y             0
FLAG_LAST_APPL_PER_CONTRACT           0
NFLAG_LAST_APPL_IN_DAY                0
RATE_DOWN_PAYMENT                749540
RATE_INTEREST_PRIMARY           1408910
RATE_INTEREST_PRIVILEGED        1408910
NAME_CASH_LOAN_PURPOSE                0
NAME_CONTRACT_STATUS                  0
DAYS_DECISION                         0
NAME_PAYMENT_TYPE                     0
CODE_REJECT_REASON                    0
NAME_TYPE_SUITE_y                694672
NAME_CLIENT_TYPE                      0
NAME_GOODS_CATEGORY                   0
NAME_PORTFOLIO                        0
NAME_PRODUCT_TYPE                     0
CHANNEL_TYPE                          0
SELLERPLACE_AREA                      0
NAME_SELLER_INDUSTRY                  0
CNT_PAYMENT                      307213
NAME_YIELD_GROUP                      0
PRODUCT_COMBINATION                 313
DAYS_FIRST_DRAWING               561106
DAYS_FIRST_DUE                   561106
DAYS_LAST_DUE_1ST_VERSION        561106
DAYS_LAST_DUE                    561106
DAYS_TERMINATION                 561106
NFLAG_INSURED_ON_APPROVAL        561106
dtype: int64

In [8]:
data.isnull().mean() * 100

SK_ID_CURR                       0.000000
TARGET                           0.000000
NAME_CONTRACT_TYPE_x             0.000000
CODE_GENDER                      0.000000
FLAG_OWN_CAR                     0.000000
FLAG_OWN_REALTY                  0.000000
CNT_CHILDREN                     0.000000
AMT_INCOME_TOTAL                 0.000000
AMT_CREDIT_x                     0.000000
AMT_ANNUITY_x                    0.006578
AMT_GOODS_PRICE_x                0.085449
NAME_TYPE_SUITE_x                0.249416
NAME_INCOME_TYPE                 0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_FAMILY_STATUS               0.000000
NAME_HOUSING_TYPE                0.000000
REGION_POPULATION_RELATIVE       0.000000
DAYS_BIRTH                       0.000000
DAYS_EMPLOYED                    0.000000
DAYS_REGISTRATION                0.000000
DAYS_ID_PUBLISH                  0.000000
OWN_CAR_AGE                     66.294499
FLAG_MOBIL                       0.000000
FLAG_EMP_PHONE                   0.000000
FLAG_WORK_PHONE                  0.000000
FLAG_CONT_MOBILE                 0.000000
FLAG_PHONE                       0.000000
FLAG_EMAIL                       0.000000
OCCUPATION_TYPE                 32.367523
CNT_FAM_MEMBERS                  0.000000
REGION_RATING_CLIENT             0.000000
REGION_RATING_CLIENT_W_CITY      0.000000
WEEKDAY_APPR_PROCESS_START_x     0.000000
HOUR_APPR_PROCESS_START_x        0.000000
REG_REGION_NOT_LIVE_REGION       0.000000
REG_REGION_NOT_WORK_REGION       0.000000
LIVE_REGION_NOT_WORK_REGION      0.000000
REG_CITY_NOT_LIVE_CITY           0.000000
REG_CITY_NOT_WORK_CITY           0.000000
LIVE_CITY_NOT_WORK_CITY          0.000000
ORGANIZATION_TYPE                0.000000
EXT_SOURCE_1                    56.366870
EXT_SOURCE_2                     0.128811
EXT_SOURCE_3                    17.107012
APARTMENTS_AVG                  50.364115
BASEMENTAREA_AVG                58.308511
YEARS_BEGINEXPLUATATION_AVG     48.431882
YEARS_BUILD_AVG                 66.298107
COMMONAREA_AVG                  69.689347
ELEVATORS_AVG                   52.996779
ENTRANCES_AVG                   49.995155
FLOORSMAX_AVG                   49.409882
FLOORSMIN_AVG                   67.670604
LANDAREA_AVG                    59.218533
LIVINGAPARTMENTS_AVG            68.214566
LIVINGAREA_AVG                  49.826661
NONLIVINGAPARTMENTS_AVG         69.296549
NONLIVINGAREA_AVG               54.860115
APARTMENTS_MODE                 50.364115
BASEMENTAREA_MODE               58.308511
YEARS_BEGINEXPLUATATION_MODE    48.431882
YEARS_BUILD_MODE                66.298107
COMMONAREA_MODE                 69.689347
ELEVATORS_MODE                  52.996779
ENTRANCES_MODE                  49.995155
FLOORSMAX_MODE                  49.409882
FLOORSMIN_MODE                  67.670604
LANDAREA_MODE                   59.218533
LIVINGAPARTMENTS_MODE           68.214566
LIVINGAREA_MODE                 49.826661
NONLIVINGAPARTMENTS_MODE        69.296549
NONLIVINGAREA_MODE              54.860115
APARTMENTS_MEDI                 50.364115
BASEMENTAREA_MEDI               58.308511
YEARS_BEGINEXPLUATATION_MEDI    48.431882
YEARS_BUILD_MEDI                66.298107
COMMONAREA_MEDI                 69.689347
ELEVATORS_MEDI                  52.996779
ENTRANCES_MEDI                  49.995155
FLOORSMAX_MEDI                  49.409882
FLOORSMIN_MEDI                  67.670604
LANDAREA_MEDI                   59.218533
LIVINGAPARTMENTS_MEDI           68.214566
LIVINGAREA_MEDI                 49.826661
NONLIVINGAPARTMENTS_MEDI        69.296549
NONLIVINGAREA_MEDI              54.860115
FONDKAPREMONT_MODE              68.216264
HOUSETYPE_MODE                  49.810108
TOTALAREA_MODE                  47.926754
WALLSMATERIAL_MODE              50.462297
EMERGENCYSTATE_MODE             47.064478
OBS_30_CNT_SOCIAL_CIRCLE         0.222536
DEF_30_CNT_SOCIAL_CIRCLE         0.222536
OBS_60_CNT_SOCIAL_CIRCLE         0.222536
DEF_60_CNT_SOCIAL_CIRCLE         0.222536
DAYS_LAST_PHONE_CHANGE           0.000000
FLAG_DOCUMENT_2                  0.000000
FLAG_DOCUMENT_3                  0.000000
FLAG_DOCUMENT_4                  0.000000
FLAG_DOCUMENT_5                  0.000000
FLAG_DOCUMENT_6                  0.000000
FLAG_DOCUMENT_7                  0.000000
FLAG_DOCUMENT_8                  0.000000
FLAG_DOCUMENT_9                  0.000000
FLAG_DOCUMENT_10                 0.000000
FLAG_DOCUMENT_11                 0.000000
FLAG_DOCUMENT_12                 0.000000
FLAG_DOCUMENT_13                 0.000000
FLAG_DOCUMENT_14                 0.000000
FLAG_DOCUMENT_15                 0.000000
FLAG_DOCUMENT_16                 0.000000
FLAG_DOCUMENT_17                 0.000000
FLAG_DOCUMENT_18                 0.000000
FLAG_DOCUMENT_19                 0.000000
FLAG_DOCUMENT_20                 0.000000
FLAG_DOCUMENT_21                 0.000000
AMT_REQ_CREDIT_BUREAU_HOUR      11.574371
AMT_REQ_CREDIT_BUREAU_DAY       11.574371
AMT_REQ_CREDIT_BUREAU_WEEK      11.574371
AMT_REQ_CREDIT_BUREAU_MON       11.574371
AMT_REQ_CREDIT_BUREAU_QRT       11.574371
AMT_REQ_CREDIT_BUREAU_YEAR      11.574371
SK_ID_PREV                       0.000000
NAME_CONTRACT_TYPE_y             0.000000
AMT_ANNUITY_y                   21.731469
AMT_APPLICATION                  0.000000
AMT_CREDIT_y                     0.000071
AMT_DOWN_PAYMENT                53.019698
AMT_GOODS_PRICE_y               22.602021
WEEKDAY_APPR_PROCESS_START_y     0.000000
HOUR_APPR_PROCESS_START_y        0.000000
FLAG_LAST_APPL_PER_CONTRACT      0.000000
NFLAG_LAST_APPL_IN_DAY           0.000000
RATE_DOWN_PAYMENT               53.019698
RATE_INTEREST_PRIMARY           99.661102
RATE_INTEREST_PRIVILEGED        99.661102
NAME_CASH_LOAN_PURPOSE           0.000000
NAME_CONTRACT_STATUS             0.000000
DAYS_DECISION                    0.000000
NAME_PAYMENT_TYPE                0.000000
CODE_REJECT_REASON               0.000000
NAME_TYPE_SUITE_y               49.138538
NAME_CLIENT_TYPE                 0.000000
NAME_GOODS_CATEGORY              0.000000
NAME_PORTFOLIO                   0.000000
NAME_PRODUCT_TYPE                0.000000
CHANNEL_TYPE                     0.000000
SELLERPLACE_AREA                 0.000000
NAME_SELLER_INDUSTRY             0.000000
CNT_PAYMENT                     21.731116
NAME_YIELD_GROUP                 0.000000
PRODUCT_COMBINATION              0.022140
DAYS_FIRST_DRAWING              39.690571
DAYS_FIRST_DUE                  39.690571
DAYS_LAST_DUE_1ST_VERSION       39.690571
DAYS_LAST_DUE                   39.690571
DAYS_TERMINATION                39.690571
NFLAG_INSURED_ON_APPROVAL       39.690571
dtype: float64

In [9]:
data1 = data.copy()

In [10]:
nn = (data1.isnull().mean() * 100)

nn = nn[nn>= 50]

null_columns = nn.index.to_list()

In [11]:
len(null_columns)

38

In [12]:
data1.drop(null_columns, axis = 1, inplace = True)

In [13]:
data1.shape

(1413701, 120)

In [14]:
data1.isnull().mean() * 100

SK_ID_CURR                       0.000000
TARGET                           0.000000
NAME_CONTRACT_TYPE_x             0.000000
CODE_GENDER                      0.000000
FLAG_OWN_CAR                     0.000000
FLAG_OWN_REALTY                  0.000000
CNT_CHILDREN                     0.000000
AMT_INCOME_TOTAL                 0.000000
AMT_CREDIT_x                     0.000000
AMT_ANNUITY_x                    0.006578
AMT_GOODS_PRICE_x                0.085449
NAME_TYPE_SUITE_x                0.249416
NAME_INCOME_TYPE                 0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_FAMILY_STATUS               0.000000
NAME_HOUSING_TYPE                0.000000
REGION_POPULATION_RELATIVE       0.000000
DAYS_BIRTH                       0.000000
DAYS_EMPLOYED                    0.000000
DAYS_REGISTRATION                0.000000
DAYS_ID_PUBLISH                  0.000000
FLAG_MOBIL                       0.000000
FLAG_EMP_PHONE                   0.000000
FLAG_WORK_PHONE                  0.000000
FLAG_CONT_MOBILE                 0.000000
FLAG_PHONE                       0.000000
FLAG_EMAIL                       0.000000
OCCUPATION_TYPE                 32.367523
CNT_FAM_MEMBERS                  0.000000
REGION_RATING_CLIENT             0.000000
REGION_RATING_CLIENT_W_CITY      0.000000
WEEKDAY_APPR_PROCESS_START_x     0.000000
HOUR_APPR_PROCESS_START_x        0.000000
REG_REGION_NOT_LIVE_REGION       0.000000
REG_REGION_NOT_WORK_REGION       0.000000
LIVE_REGION_NOT_WORK_REGION      0.000000
REG_CITY_NOT_LIVE_CITY           0.000000
REG_CITY_NOT_WORK_CITY           0.000000
LIVE_CITY_NOT_WORK_CITY          0.000000
ORGANIZATION_TYPE                0.000000
EXT_SOURCE_2                     0.128811
EXT_SOURCE_3                    17.107012
YEARS_BEGINEXPLUATATION_AVG     48.431882
ENTRANCES_AVG                   49.995155
FLOORSMAX_AVG                   49.409882
LIVINGAREA_AVG                  49.826661
YEARS_BEGINEXPLUATATION_MODE    48.431882
ENTRANCES_MODE                  49.995155
FLOORSMAX_MODE                  49.409882
LIVINGAREA_MODE                 49.826661
YEARS_BEGINEXPLUATATION_MEDI    48.431882
ENTRANCES_MEDI                  49.995155
FLOORSMAX_MEDI                  49.409882
LIVINGAREA_MEDI                 49.826661
HOUSETYPE_MODE                  49.810108
TOTALAREA_MODE                  47.926754
EMERGENCYSTATE_MODE             47.064478
OBS_30_CNT_SOCIAL_CIRCLE         0.222536
DEF_30_CNT_SOCIAL_CIRCLE         0.222536
OBS_60_CNT_SOCIAL_CIRCLE         0.222536
DEF_60_CNT_SOCIAL_CIRCLE         0.222536
DAYS_LAST_PHONE_CHANGE           0.000000
FLAG_DOCUMENT_2                  0.000000
FLAG_DOCUMENT_3                  0.000000
FLAG_DOCUMENT_4                  0.000000
FLAG_DOCUMENT_5                  0.000000
FLAG_DOCUMENT_6                  0.000000
FLAG_DOCUMENT_7                  0.000000
FLAG_DOCUMENT_8                  0.000000
FLAG_DOCUMENT_9                  0.000000
FLAG_DOCUMENT_10                 0.000000
FLAG_DOCUMENT_11                 0.000000
FLAG_DOCUMENT_12                 0.000000
FLAG_DOCUMENT_13                 0.000000
FLAG_DOCUMENT_14                 0.000000
FLAG_DOCUMENT_15                 0.000000
FLAG_DOCUMENT_16                 0.000000
FLAG_DOCUMENT_17                 0.000000
FLAG_DOCUMENT_18                 0.000000
FLAG_DOCUMENT_19                 0.000000
FLAG_DOCUMENT_20                 0.000000
FLAG_DOCUMENT_21                 0.000000
AMT_REQ_CREDIT_BUREAU_HOUR      11.574371
AMT_REQ_CREDIT_BUREAU_DAY       11.574371
AMT_REQ_CREDIT_BUREAU_WEEK      11.574371
AMT_REQ_CREDIT_BUREAU_MON       11.574371
AMT_REQ_CREDIT_BUREAU_QRT       11.574371
AMT_REQ_CREDIT_BUREAU_YEAR      11.574371
SK_ID_PREV                       0.000000
NAME_CONTRACT_TYPE_y             0.000000
AMT_ANNUITY_y                   21.731469
AMT_APPLICATION                  0.000000
AMT_CREDIT_y                     0.000071
AMT_GOODS_PRICE_y               22.602021
WEEKDAY_APPR_PROCESS_START_y     0.000000
HOUR_APPR_PROCESS_START_y        0.000000
FLAG_LAST_APPL_PER_CONTRACT      0.000000
NFLAG_LAST_APPL_IN_DAY           0.000000
NAME_CASH_LOAN_PURPOSE           0.000000
NAME_CONTRACT_STATUS             0.000000
DAYS_DECISION                    0.000000
NAME_PAYMENT_TYPE                0.000000
CODE_REJECT_REASON               0.000000
NAME_TYPE_SUITE_y               49.138538
NAME_CLIENT_TYPE                 0.000000
NAME_GOODS_CATEGORY              0.000000
NAME_PORTFOLIO                   0.000000
NAME_PRODUCT_TYPE                0.000000
CHANNEL_TYPE                     0.000000
SELLERPLACE_AREA                 0.000000
NAME_SELLER_INDUSTRY             0.000000
CNT_PAYMENT                     21.731116
NAME_YIELD_GROUP                 0.000000
PRODUCT_COMBINATION              0.022140
DAYS_FIRST_DRAWING              39.690571
DAYS_FIRST_DUE                  39.690571
DAYS_LAST_DUE_1ST_VERSION       39.690571
DAYS_LAST_DUE                   39.690571
DAYS_TERMINATION                39.690571
NFLAG_INSURED_ON_APPROVAL       39.690571
dtype: float64

In [15]:
data1.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_2,EXT_SOURCE_3,YEARS_BEGINEXPLUATATION_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,LIVINGAREA_AVG,YEARS_BEGINEXPLUATATION_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,LIVINGAREA_MODE,YEARS_BEGINEXPLUATATION_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,LIVINGAREA_MEDI,HOUSETYPE_MODE,TOTALAREA_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.262949,0.139376,0.9722,0.0690,0.0833,0.0190,0.9722,0.0690,0.0833,0.0198,0.9722,0.0690,0.0833,0.0193,block of flats,0.0149,No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1038818,Consumer loans,9251.775,179055.0,179055.0,179055.0,SATURDAY,9,Y,1,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.622246,NaN,0.9851,0.0345,0.2917,0.0549,0.9851,0.0345,0.2917,0.0554,0.9851,0.0345,0.2917,0.0558,block of flats,0.0714,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,900000.0,FRIDAY,12,Y,1,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.622246,NaN,0.9851,0.0345,0.2917,0.0549,0.9851,0.0345,0.2917,0.0554,0.9851,0.0345,0.2917,0.0558,block of flats,0.0714,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,337500.0,SUNDAY,17,Y,1,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.622246,NaN,0.9851,0.0345,0.2917,0.0549,0.9851,0.0345,0.2917,0.0554,0.9851,0.0345,0.2917,0.0558,block of flats,0.0714,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,68809.5,SATURDAY,15,Y,1,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1564014,Consumer loans,5357.250,24282.0,20106.0,24282.0,FRIDAY,5,Y,1,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0

In [16]:
unwanted_columns = ['EXT_SOURCE_2', 'EXT_SOURCE_3', 'YEARS_BEGINEXPLUATATION_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'LIVINGAREA_AVG', 'YEARS_BEGINEXPLUATATION_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'LIVINGAREA_MODE', 'YEARS_BEGINEXPLUATATION_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'LIVINGAREA_MEDI', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'EMERGENCYSTATE_MODE']

In [17]:
len(unwanted_columns)

17

In [18]:
data1.drop(unwanted_columns, axis=1, inplace=True)

In [19]:
data1.shape

(1413701, 103)

In [20]:
data1.isnull().mean() * 100

SK_ID_CURR                       0.000000
TARGET                           0.000000
NAME_CONTRACT_TYPE_x             0.000000
CODE_GENDER                      0.000000
FLAG_OWN_CAR                     0.000000
FLAG_OWN_REALTY                  0.000000
CNT_CHILDREN                     0.000000
AMT_INCOME_TOTAL                 0.000000
AMT_CREDIT_x                     0.000000
AMT_ANNUITY_x                    0.006578
AMT_GOODS_PRICE_x                0.085449
NAME_TYPE_SUITE_x                0.249416
NAME_INCOME_TYPE                 0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_FAMILY_STATUS               0.000000
NAME_HOUSING_TYPE                0.000000
REGION_POPULATION_RELATIVE       0.000000
DAYS_BIRTH                       0.000000
DAYS_EMPLOYED                    0.000000
DAYS_REGISTRATION                0.000000
DAYS_ID_PUBLISH                  0.000000
FLAG_MOBIL                       0.000000
FLAG_EMP_PHONE                   0.000000
FLAG_WORK_PHONE                  0.000000
FLAG_CONT_MOBILE                 0.000000
FLAG_PHONE                       0.000000
FLAG_EMAIL                       0.000000
OCCUPATION_TYPE                 32.367523
CNT_FAM_MEMBERS                  0.000000
REGION_RATING_CLIENT             0.000000
REGION_RATING_CLIENT_W_CITY      0.000000
WEEKDAY_APPR_PROCESS_START_x     0.000000
HOUR_APPR_PROCESS_START_x        0.000000
REG_REGION_NOT_LIVE_REGION       0.000000
REG_REGION_NOT_WORK_REGION       0.000000
LIVE_REGION_NOT_WORK_REGION      0.000000
REG_CITY_NOT_LIVE_CITY           0.000000
REG_CITY_NOT_WORK_CITY           0.000000
LIVE_CITY_NOT_WORK_CITY          0.000000
ORGANIZATION_TYPE                0.000000
OBS_30_CNT_SOCIAL_CIRCLE         0.222536
DEF_30_CNT_SOCIAL_CIRCLE         0.222536
OBS_60_CNT_SOCIAL_CIRCLE         0.222536
DEF_60_CNT_SOCIAL_CIRCLE         0.222536
DAYS_LAST_PHONE_CHANGE           0.000000
FLAG_DOCUMENT_2                  0.000000
FLAG_DOCUMENT_3                  0.000000
FLAG_DOCUMENT_4                  0.000000
FLAG_DOCUMENT_5                  0.000000
FLAG_DOCUMENT_6                  0.000000
FLAG_DOCUMENT_7                  0.000000
FLAG_DOCUMENT_8                  0.000000
FLAG_DOCUMENT_9                  0.000000
FLAG_DOCUMENT_10                 0.000000
FLAG_DOCUMENT_11                 0.000000
FLAG_DOCUMENT_12                 0.000000
FLAG_DOCUMENT_13                 0.000000
FLAG_DOCUMENT_14                 0.000000
FLAG_DOCUMENT_15                 0.000000
FLAG_DOCUMENT_16                 0.000000
FLAG_DOCUMENT_17                 0.000000
FLAG_DOCUMENT_18                 0.000000
FLAG_DOCUMENT_19                 0.000000
FLAG_DOCUMENT_20                 0.000000
FLAG_DOCUMENT_21                 0.000000
AMT_REQ_CREDIT_BUREAU_HOUR      11.574371
AMT_REQ_CREDIT_BUREAU_DAY       11.574371
AMT_REQ_CREDIT_BUREAU_WEEK      11.574371
AMT_REQ_CREDIT_BUREAU_MON       11.574371
AMT_REQ_CREDIT_BUREAU_QRT       11.574371
AMT_REQ_CREDIT_BUREAU_YEAR      11.574371
SK_ID_PREV                       0.000000
NAME_CONTRACT_TYPE_y             0.000000
AMT_ANNUITY_y                   21.731469
AMT_APPLICATION                  0.000000
AMT_CREDIT_y                     0.000071
AMT_GOODS_PRICE_y               22.602021
WEEKDAY_APPR_PROCESS_START_y     0.000000
HOUR_APPR_PROCESS_START_y        0.000000
FLAG_LAST_APPL_PER_CONTRACT      0.000000
NFLAG_LAST_APPL_IN_DAY           0.000000
NAME_CASH_LOAN_PURPOSE           0.000000
NAME_CONTRACT_STATUS             0.000000
DAYS_DECISION                    0.000000
NAME_PAYMENT_TYPE                0.000000
CODE_REJECT_REASON               0.000000
NAME_TYPE_SUITE_y               49.138538
NAME_CLIENT_TYPE                 0.000000
NAME_GOODS_CATEGORY              0.000000
NAME_PORTFOLIO                   0.000000
NAME_PRODUCT_TYPE                0.000000
CHANNEL_TYPE                     0.000000
SELLERPLACE_AREA                 0.000000
NAME_SELLER_INDUSTRY             0.000000
CNT_PAYMENT                     21.731116
NAME_YIELD_GROUP                 0.000000
PRODUCT_COMBINATION              0.022140
DAYS_FIRST_DRAWING              39.690571
DAYS_FIRST_DUE                  39.690571
DAYS_LAST_DUE_1ST_VERSION       39.690571
DAYS_LAST_DUE                   39.690571
DAYS_TERMINATION                39.690571
NFLAG_INSURED_ON_APPROVAL       39.690571
dtype: float64

In [21]:
data1.info(object)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413701 entries, 0 to 1413700
Data columns (total 103 columns):
 #    Column                        Dtype
---   ------                        -----
 0    SK_ID_CURR                    int64
 1    TARGET                        int64
 2    NAME_CONTRACT_TYPE_x          object
 3    CODE_GENDER                   object
 4    FLAG_OWN_CAR                  object
 5    FLAG_OWN_REALTY               object
 6    CNT_CHILDREN                  int64
 7    AMT_INCOME_TOTAL              float64
 8    AMT_CREDIT_x                  float64
 9    AMT_ANNUITY_x                 float64
 10   AMT_GOODS_PRICE_x             float64
 11   NAME_TYPE_SUITE_x             object
 12   NAME_INCOME_TYPE              object
 13   NAME_EDUCATION_TYPE           object
 14   NAME_FAMILY_STATUS            object
 15   NAME_HOUSING_TYPE             object
 16   REGION_POPULATION_RELATIVE    float64
 17   DAYS_BIRTH                    int64
 18   DAYS_EMPLOYED                 int64
 19   DAYS_REGISTRATION             float64
 20   DAYS_ID_PUBLISH               int64
 21   FLAG_MOBIL                    int64
 22   FLAG_EMP_PHONE                int64
 23   FLAG_WORK_PHONE               int64
 24   FLAG_CONT_MOBILE              int64
 25   FLAG_PHONE                    int64
 26   FLAG_EMAIL                    int64
 27   OCCUPATION_TYPE               object
 28   CNT_FAM_MEMBERS               float64
 29   REGION_RATING_CLIENT          int64
 30   REGION_RATING_CLIENT_W_CITY   int64
 31   WEEKDAY_APPR_PROCESS_START_x  object
 32   HOUR_APPR_PROCESS_START_x     int64
 33   REG_REGION_NOT_LIVE_REGION    int64
 34   REG_REGION_NOT_WORK_REGION    int64
 35   LIVE_REGION_NOT_WORK_REGION   int64
 36   REG_CITY_NOT_LIVE_CITY        int64
 37   REG_CITY_NOT_WORK_CITY        int64
 38   LIVE_CITY_NOT_WORK_CITY       int64
 39   ORGANIZATION_TYPE             object
 40   OBS_30_CNT_SOCIAL_CIRCLE      float64
 41   DEF_30_CNT_SOCIAL_CIRCLE      float64
 42   OBS_60_CNT_SOCIAL_CIRCLE      float64
 43   DEF_60_CNT_SOCIAL_CIRCLE      float64
 44   DAYS_LAST_PHONE_CHANGE        float64
 45   FLAG_DOCUMENT_2               int64
 46   FLAG_DOCUMENT_3               int64
 47   FLAG_DOCUMENT_4               int64
 48   FLAG_DOCUMENT_5               int64
 49   FLAG_DOCUMENT_6               int64
 50   FLAG_DOCUMENT_7               int64
 51   FLAG_DOCUMENT_8               int64
 52   FLAG_DOCUMENT_9               int64
 53   FLAG_DOCUMENT_10              int64
 54   FLAG_DOCUMENT_11              int64
 55   FLAG_DOCUMENT_12              int64
 56   FLAG_DOCUMENT_13              int64
 57   FLAG_DOCUMENT_14              int64
 58   FLAG_DOCUMENT_15              int64
 59   FLAG_DOCUMENT_16              int64
 60   FLAG_DOCUMENT_17              int64
 61   FLAG_DOCUMENT_18              int64
 62   FLAG_DOCUMENT_19              int64
 63   FLAG_DOCUMENT_20              int64
 64   FLAG_DOCUMENT_21              int64
 65   AMT_REQ_CREDIT_BUREAU_HOUR    float64
 66   AMT_REQ_CREDIT_BUREAU_DAY     float64
 67   AMT_REQ_CREDIT_BUREAU_WEEK    float64
 68   AMT_REQ_CREDIT_BUREAU_MON     float64
 69   AMT_REQ_CREDIT_BUREAU_QRT     float64
 70   AMT_REQ_CREDIT_BUREAU_YEAR    float64
 71   SK_ID_PREV                    int64
 72   NAME_CONTRACT_TYPE_y          object
 73   AMT_ANNUITY_y                 float64
 74   AMT_APPLICATION               float64
 75   AMT_CREDIT_y                  float64
 76   AMT_GOODS_PRICE_y             float64
 77   WEEKDAY_APPR_PROCESS_START_y  object
 78   HOUR_APPR_PROCESS_START_y     int64
 79   FLAG_LAST_APPL_PER_CONTRACT   object
 80   NFLAG_LAST_APPL_IN_DAY        int64
 81   NAME_CASH_LOAN_PURPOSE        object
 82   NAME_CONTRACT_STATUS          object
 83   DAYS_DECISION                 int64
 84   NAME_PAYMENT_TYPE             object
 85   CODE_REJECT_REASON            object
 86   NAME_TYPE_SUITE_y             object
 87   NAME_CLIENT_TYPE              object
 88   NAME_GOODS_CATEGORY           object
 89   NAME_PORTFOLIO                object
 90   NAME_PRODUCT_TYPE             object
 91   CHANNEL_TYPE                  object
 92   SELLERPLACE_AREA              int64
 93   NAME_SELLER_INDUSTRY          object
 94   CNT_PAYMENT                   float64
 95   NAME_YIELD_GROUP              object
 96   PRODUCT_COMBINATION           object
 97   DAYS_FIRST_DRAWING            float64
 98   DAYS_FIRST_DUE                float64
 99   DAYS_LAST_DUE_1ST_VERSION     float64
 100  DAYS_LAST_DUE                 float64
 101  DAYS_TERMINATION              float64
 102  NFLAG_INSURED_ON_APPROVAL     float64
dtypes: float64(29), int64(46), object(28)
memory usage: 1.1+ GB

In [22]:
data1.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_TYPE_SUITE_x,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START_x,HOUR_APPR_PROCESS_START_x,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_PREV,NAME_CONTRACT_TYPE_y,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_GOODS_PRICE_y,WEEKDAY_APPR_PROCESS_START_y,HOUR_APPR_PROCESS_START_y,FLAG_LAST_APPL_PER_CONTRACT,NFLAG_LAST_APPL_IN_DAY,NAME_CASH_LOAN_PURPOSE,NAME_CONTRACT_STATUS,DAYS_DECISION,NAME_PAYMENT_TYPE,CODE_REJECT_REASON,NAME_TYPE_SUITE_y,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,NAME_PORTFOLIO,NAME_PRODUCT_TYPE,CHANNEL_TYPE,SELLERPLACE_AREA,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,1038818,Consumer loans,9251.775,179055.0,179055.0,179055.0,SATURDAY,9,Y,1,XAP,Approved,-606,XNA,XAP,NaN,New,Vehicles,POS,XNA,Stone,500,Auto technology,24.0,low_normal,POS other with interest,365243.0,-565.0,125.0,-25.0,-17.0,0.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1810518,Cash loans,98356.995,900000.0,1035882.0,900000.0,FRIDAY,12,Y,1,XNA,Approved,-746,XNA,XAP,Unaccompanied,Repeater,XNA,Cash,x-sell,Credit and cash offices,-1,XNA,12.0,low_normal,Cash X-Sell: low,365243.0,-716.0,-386.0,-536.0,-527.0,1.0
2,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2636178,Consumer loans,64567.665,337500.0,348637.5,337500.0,SUNDAY,17,Y,1,XAP,Approved,-828,Cash through the bank,XAP,Family,Refreshed,Furniture,POS,XNA,Stone,1400,Furniture,6.0,middle,POS industry with interest,365243.0,-797.0,-647.0,-647.0,-639.0,0.0
3,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,2396755,Consumer loans,6737.310,68809.5,68053.5,68809.5,SATURDAY,15,Y,1,XAP,Approved,-2341,Cash through the bank,XAP,Family,Refreshed,Consumer Electronics,POS,XNA,Country-wide,200,Consumer electronics,12.0,middle,POS household with interest,365243.0,-2310.0,-1980.0,-1980.0,-1976.0,1.0
4,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1564014,Consumer loans,5357.250,24282.0,20106.0,24282.0,FRIDAY,5,Y,1,XAP,Approved,-815,Cash through the bank,XAP,Unaccompanied,New,Mobile,POS,XNA,Regional / Local,30,Connectivity,4.0,middle,POS mobile without interest,365243.0,-784.0,-694.0,-724.0,-714.0,0.0

In [23]:
unwanted_columns2 = ["CNT_CHILDREN","REGION_POPULATION_RELATIVE","DAYS_ID_PUBLISH","OWN_CAR_AGE","REGION_RATING_CLIENT","REGION_RATING_CLIENT_W_CITY","WEEKDAY_APPR_PROCESS_START","HOUR_APPR_PROCESS_START","FLAG_DOCUMENT_2","FLAG_DOCUMENT_3","FLAG_DOCUMENT_4","FLAG_DOCUMENT_5","FLAG_DOCUMENT_6","FLAG_DOCUMENT_7","FLAG_DOCUMENT_8","FLAG_DOCUMENT_9","FLAG_DOCUMENT_10","FLAG_DOCUMENT_11","FLAG_DOCUMENT_12","FLAG_DOCUMENT_13","FLAG_DOCUMENT_14","FLAG_DOCUMENT_15","FLAG_DOCUMENT_16","FLAG_DOCUMENT_17","FLAG_DOCUMENT_18","FLAG_DOCUMENT_19","FLAG_DOCUMENT_20","FLAG_DOCUMENT_21","WEEKDAY_APPR_PROCESS_START","HOUR_APPR_PROCESS_START","NAME_TYPE_SUITE","NAME_PRODUCT_TYPE","SELLERPLACE_AREA","PRODUCT_COMBINATION"]

In [24]:
len(unwanted_columns2)

34

In [25]:
for i in unwanted_columns2:
    if i in data1:
        data1.drop(i, axis=1, inplace=True)

In [26]:
data1.shape

(1413701, 75)

In [27]:
data1.to_csv("Cleaned_data_1.csv")