In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score
from imblearn.over_sampling import SMOTE, RandomOverSampler
import pickle

In [2]:
data = pd.read_csv("F:\GUVI\Project\FINAL PROJECT\Final_cleaned_data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\syeda\AppData\Local\Temp\ipykernel_23976\1217478590.py:1: SyntaxWarning: invalid escape sequence '\G'
  data = pd.read_csv("F:\GUVI\Project\FINAL PROJECT\Final_cleaned_data.csv")

In [3]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [4]:
data.head()

,TARGET,NAME_CONTRACT_TYPE_x,CODE_GENDER,AMT_INCOME_TOTAL,AMT_CREDIT_x,AMT_ANNUITY_x,AMT_GOODS_PRICE_x,NAME_INCOME_TYPE,FLAG_MOBIL,FLAG_CONT_MOBILE,FLAG_EMAIL,OCCUPATION_TYPE,ORGANIZATION_TYPE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,AMT_ANNUITY_y,AMT_APPLICATION,AMT_CREDIT_y,AMT_GOODS_PRICE_y,FLAG_LAST_APPL_PER_CONTRACT,NAME_CONTRACT_STATUS,NFLAG_INSURED_ON_APPROVAL,DAYS_BIRTH_YEARS,DAYS_EMPLOYED_YEARS,DAYS_REGISTRATION_YEARS,DAYS_ID_PUBLISH_YEARS,DAYS_LAST_PHONE_CHANGE_YEARS,DAYS_DECISION_YEARS
0,1,Cash loans,M,202500.0,406597.5,24700.5,351000.0,Working,1,1,0,Laborers,Business Entity Type 3,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,9251.775,179055.0,179055.0,179055.0,Y,Approved,0.0,25.9,1.7,10.0,5.8,3.1,1.7
1,0,Cash loans,F,270000.0,1293502.5,35698.5,1129500.0,State servant,1,1,0,Core staff,School,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,98356.995,900000.0,1035882.0,900000.0,Y,Approved,1.0,45.9,3.3,3.2,0.8,2.3,2.0
2,0,Cash loans,F,270000.0,1293502.5,35698.5,1129500.0,State servant,1,1,0,Core staff,School,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64567.665,337500.0,348637.5,337500.0,Y,Approved,0.0,45.9,3.3,3.2,0.8,2.3,2.3
3,0,Cash loans,F,270000.0,1293502.5,35698.5,1129500.0,State servant,1,1,0,Core staff,School,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6737.310,68809.5,68053.5,68809.5,Y,Approved,1.0,45.9,3.3,3.2,0.8,2.3,6.4
4,0,Revolving loans,M,67500.0,135000.0,6750.0,135000.0,Working,1,1,0,Laborers,Government,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5357.250,24282.0,20106.0,24282.0,Y,Approved,0.0,52.1,0.6,11.7,6.9,2.2,2.2

In [5]:
data.shape

(1303167, 36)

In [6]:
impt_feat = ["TARGET","NFLAG_INSURED_ON_APPROVAL", "AMT_REQ_CREDIT_BUREAU_YEAR", "AMT_CREDIT_x", "DAYS_BIRTH_YEARS", "AMT_ANNUITY_y", "DAYS_LAST_PHONE_CHANGE_YEARS", "AMT_ANNUITY_x", "NAME_CONTRACT_STATUS", "AMT_INCOME_TOTAL", "DAYS_ID_PUBLISH_YEARS", "OBS_60_CNT_SOCIAL_CIRCLE", "NAME_CONTRACT_TYPE_x", "OCCUPATION_TYPE"]

In [7]:
len(impt_feat)

14

In [8]:
data = data[impt_feat]

In [9]:
data.shape

(1303167, 14)

In [10]:
data.duplicated().sum()

70059

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data.head()

,TARGET,NFLAG_INSURED_ON_APPROVAL,AMT_REQ_CREDIT_BUREAU_YEAR,AMT_CREDIT_x,DAYS_BIRTH_YEARS,AMT_ANNUITY_y,DAYS_LAST_PHONE_CHANGE_YEARS,AMT_ANNUITY_x,NAME_CONTRACT_STATUS,AMT_INCOME_TOTAL,DAYS_ID_PUBLISH_YEARS,OBS_60_CNT_SOCIAL_CIRCLE,NAME_CONTRACT_TYPE_x,OCCUPATION_TYPE
0,1,0.0,1.0,406597.5,25.9,9251.775,3.1,24700.5,Approved,202500.0,5.8,2.0,Cash loans,Laborers
1,0,1.0,0.0,1293502.5,45.9,98356.995,2.3,35698.5,Approved,270000.0,0.8,1.0,Cash loans,Core staff
2,0,0.0,0.0,1293502.5,45.9,64567.665,2.3,35698.5,Approved,270000.0,0.8,1.0,Cash loans,Core staff
3,0,1.0,0.0,1293502.5,45.9,6737.310,2.3,35698.5,Approved,270000.0,0.8,1.0,Cash loans,Core staff
4,0,0.0,0.0,135000.0,52.1,5357.250,2.2,6750.0,Approved,67500.0,6.9,0.0,Revolving loans,Laborers

In [13]:
data["NAME_CONTRACT_STATUS"].value_counts()

NAME_CONTRACT_STATUS
Approved        882431
Refused         215351
Canceled        116084
Unused offer     19242
Name: count, dtype: int64

In [14]:
data["NAME_CONTRACT_TYPE_x"].value_counts()

NAME_CONTRACT_TYPE_x
Cash loans         1138645
Revolving loans      94463
Name: count, dtype: int64

In [15]:
data["OCCUPATION_TYPE"].value_counts()

OCCUPATION_TYPE
Laborers                 615727
Sales staff              131742
Core staff               104279
Managers                  83128
Drivers                   73778
High skill tech staff     42852
Accountants               36887
Medicine staff            35203
Security staff            27687
Cooking staff             25149
Cleaning staff            20937
Private service staff     10578
Low-skill Laborers         8121
Waiters/barmen staff       5384
Secretaries                5049
Realty agents              3065
HR staff                   1994
IT staff                   1548
Name: count, dtype: int64

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1233108 entries, 0 to 1303166
Data columns (total 14 columns):
 #   Column                        Non-Null Count    Dtype
---  ------                        --------------    -----
 0   TARGET                        1233108 non-null  int64
 1   NFLAG_INSURED_ON_APPROVAL     1233108 non-null  float64
 2   AMT_REQ_CREDIT_BUREAU_YEAR    1233108 non-null  float64
 3   AMT_CREDIT_x                  1233108 non-null  float64
 4   DAYS_BIRTH_YEARS              1233108 non-null  float64
 5   AMT_ANNUITY_y                 1233108 non-null  float64
 6   DAYS_LAST_PHONE_CHANGE_YEARS  1233108 non-null  float64
 7   AMT_ANNUITY_x                 1233108 non-null  float64
 8   NAME_CONTRACT_STATUS          1233108 non-null  object
 9   AMT_INCOME_TOTAL              1233108 non-null  float64
 10  DAYS_ID_PUBLISH_YEARS         1233108 non-null  float64
 11  OBS_60_CNT_SOCIAL_CIRCLE      1233108 non-null  float64
 12  NAME_CONTRACT_TYPE_x          1233108 non-null  object
 13  OCCUPATION_TYPE               1233108 non-null  object
dtypes: float64(10), int64(1), object(3)
memory usage: 141.1+ MB

In [17]:
label_encoders = {}
for i in data.select_dtypes(include='object'):
    le = LabelEncoder()
    data[i] = le.fit_transform(data[i])
    label_encoders[i] = le

In [18]:
label_encoders

{'NAME_CONTRACT_STATUS': LabelEncoder(),
 'NAME_CONTRACT_TYPE_x': LabelEncoder(),
 'OCCUPATION_TYPE': LabelEncoder()}

In [19]:
with open("label_encoders.pkl",'wb') as file:
    pickle.dump(label_encoders, file)

In [ ]:
# le = LabelEncoder()
# for i in data.select_dtypes(include='object'):
#     data[i] = le.fit_transform(data[i])

In [32]:
data.head()

,TARGET,NFLAG_INSURED_ON_APPROVAL,AMT_REQ_CREDIT_BUREAU_YEAR,AMT_CREDIT_x,DAYS_BIRTH_YEARS,AMT_ANNUITY_y,DAYS_LAST_PHONE_CHANGE_YEARS,AMT_ANNUITY_x,NAME_CONTRACT_STATUS,AMT_INCOME_TOTAL,DAYS_ID_PUBLISH_YEARS,OBS_60_CNT_SOCIAL_CIRCLE,NAME_CONTRACT_TYPE_x,OCCUPATION_TYPE
0,1,0.0,1.0,406597.5,25.9,9251.775,3.1,24700.5,0,202500.0,5.8,2.0,0,8
1,0,1.0,0.0,1293502.5,45.9,98356.995,2.3,35698.5,0,270000.0,0.8,1.0,0,3
2,0,0.0,0.0,1293502.5,45.9,64567.665,2.3,35698.5,0,270000.0,0.8,1.0,0,3
3,0,1.0,0.0,1293502.5,45.9,6737.310,2.3,35698.5,0,270000.0,0.8,1.0,0,3
4,0,0.0,0.0,135000.0,52.1,5357.250,2.2,6750.0,0,67500.0,6.9,0.0,1,8

In [33]:
features_cols = ["AMT_CREDIT_x", "AMT_ANNUITY_y", "AMT_ANNUITY_x","AMT_INCOME_TOTAL"]

In [34]:
mm = MinMaxScaler()
data[features_cols] = mm.fit_transform(data[features_cols])

In [35]:
data.head()

,TARGET,NFLAG_INSURED_ON_APPROVAL,AMT_REQ_CREDIT_BUREAU_YEAR,AMT_CREDIT_x,DAYS_BIRTH_YEARS,AMT_ANNUITY_y,DAYS_LAST_PHONE_CHANGE_YEARS,AMT_ANNUITY_x,NAME_CONTRACT_STATUS,AMT_INCOME_TOTAL,DAYS_ID_PUBLISH_YEARS,OBS_60_CNT_SOCIAL_CIRCLE,NAME_CONTRACT_TYPE_x,OCCUPATION_TYPE
0,1,0.0,1.0,0.090287,25.9,0.022130,3.1,0.103342,0,0.001512,5.8,2.0,0,8
1,0,1.0,0.0,0.311736,45.9,0.235271,2.3,0.152575,0,0.002089,0.8,1.0,0,3
2,0,0.0,0.0,0.311736,45.9,0.154447,2.3,0.152575,0,0.002089,0.8,1.0,0,3
3,0,1.0,0.0,0.311736,45.9,0.016116,2.3,0.152575,0,0.002089,0.8,1.0,0,3
4,0,0.0,0.0,0.022472,52.1,0.012815,2.2,0.022985,0,0.000358,6.9,0.0,1,8

In [36]:
val = data.drop("TARGET", axis=1)
tar = data["TARGET"]

In [37]:
tar.value_counts()

TARGET
0    1129465
1     103643
Name: count, dtype: int64

In [38]:
os = SMOTE(random_state=76)
os_val, os_tar = os.fit_resample(val, tar)

In [39]:
os_tar.value_counts()

TARGET
1    1129465
0    1129465
Name: count, dtype: int64

In [40]:
train_data, test_data, train_lab, test_lab = train_test_split(os_val, os_tar, test_size=0.20, random_state=74)

In [41]:
def get_perform(actual, predict):
    acc_score = accuracy_score(actual, predict)
    prec_score = precision_score(actual, predict,average='macro')
    rec_score = recall_score(actual, predict,average='macro')
    f1 = f1_score(actual, predict, average='macro')
    return pd.DataFrame({
        "accuracy_score":[acc_score],
        "precision_score":[prec_score],
        "recall_score": [rec_score],
        "f1_score":[f1]
    })

In [42]:
# GradientBoostingClassifier

gbc = GradientBoostingClassifier(learning_rate=0.4, n_estimators=200, max_depth=10, random_state=67)
gbc.fit(train_data, train_lab)
gbc_train_pred = gbc.predict(train_data)
gbc_test_pred = gbc.predict(test_data)

In [43]:
get_perform(train_lab, gbc_train_pred)

   accuracy_score  precision_score  recall_score  f1_score
0         0.97756          0.97769      0.977561  0.977559

In [44]:
get_perform(test_lab, gbc_test_pred)

   accuracy_score  precision_score  recall_score  f1_score
0        0.968507         0.968696      0.968501  0.968504

In [45]:
# XGBClassifier

xgbc = XGBClassifier(learning_rate=0.4, n_estimators=200, max_depth=10, random_state=67)
xgbc.fit(train_data, train_lab)
xgbc_train_pred = xgbc.predict(train_data)
xgbc_test_pred = xgbc.predict(test_data)

In [46]:
get_perform(train_lab, xgbc_train_pred)

   accuracy_score  precision_score  recall_score  f1_score
0        0.969914         0.970151      0.969916  0.969911

In [47]:
get_perform(test_lab, xgbc_test_pred)

   accuracy_score  precision_score  recall_score  f1_score
0        0.962593         0.962864      0.962585  0.962587

In [48]:
import pickle

In [50]:
with open("minmax_scaler.pkl",'wb') as file:
    pickle.dump(mm, file)

In [51]:
with open("FinalGradientBoostingClassifierr.pkl", "wb") as file:
    pickle.dump(gbc, file)

In [52]:
with open("FinalXGBClassifier.pkl", "wb") as file:
    pickle.dump(xgbc, file)

In [ ]:
# Testing the models

In [101]:
with open("F:\GUVI\Project\FINAL PROJECT\CODES\FinalGradientBoostingClassifierr.pkl", "rb") as model:
    xgbcmodel = pickle.load(model)

<>:1: SyntaxWarning: invalid escape sequence '\G'
<>:1: SyntaxWarning: invalid escape sequence '\G'
C:\Users\syeda\AppData\Local\Temp\ipykernel_20844\532200721.py:1: SyntaxWarning: invalid escape sequence '\G'
  with open("F:\GUVI\Project\FINAL PROJECT\CODES\FinalGradientBoostingClassifierr.pkl", "rb") as model:

In [102]:
xgbcmodel

GradientBoostingClassifier(learning_rate=0.4, max_depth=10, n_estimators=200,
                           random_state=67)

In [ ]:
"""

1 - 155 159 405-1 1303157-1 1303073 1303032-1 1302999-1

0 - 172 180 419 1303147 1303079 1303042 1303012

"""

'\n\n1 - 155 159 405 1303157 1303073 1303032 1302999\n\n0 - 172 180 419 1303147 1303079 1303042 1303012\n\n'

In [170]:
sample_row  = data.loc[[1303012]].drop('TARGET', axis=1)

In [171]:
predicted_scaled = xgbcmodel.predict(sample_row)

In [172]:
predicted_scaled

array([0], dtype=int64)